# Q34

## title

Which option corresponds to the execution result?

## body

**Given the following code:**

```
CustomError = Class.new(StandardError)

def boom
  raise CustomError 
rescue
  raise
end

begin 
  boom
rescue => e
  p e.class
end
```

## options

### A+

`CustomError`

### B

`StandardError`

### C

`Exception`

### D

`RuntimeError`

### E

`SyntaxError`

## comment

When `raise` is called within a `rescue` branch without specifying an exception type, the raised exception type will match whatever exception was rescued.

When `raise` is called and there has not been any exceptions rescued in the current context, `RuntimeError` will be raised by default.